### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by mariusa** [intlify/vue-i18n-loader#104]
```
npm i --save-dev vue-i18n-loader
```

There's no conflict with the other project, which is marked deprecated

**Comment by kazupon** [comment]
Thank you for your PR!
`vue-i18n-loader` is not my project. `@kazupon/vue-i18n-loader` is previous my project.

**Comment by kazupon** [comment]
See the NPM:
https://www.npmjs.com/package/@kazupon/vue-i18n-loader

**Comment by mariusa** [comment]
Hi & thanks,

I see now that this https://www.npmjs.com/package/vue-i18n-loader also exists
and isn't the same as https://github.com/intlify/vue-i18n-loader

It would be great to get the old https://www.npmjs.com/package/vue-i18n-loader removed from npm. I don't see how to report it, besides a 'security vulnerability', which I reported now.

**Comment by mariusa** [comment]
Got a reply: If the maintainers would like to own the ```vue-i18n-loader``` package name they may follow npm's Package Name Dispute process: https://docs.npmjs.com/using-npm/disputes.html.

**Comment by kazupon** [comment]
Thank you very much.
It's intentional to use `@intlify/vue-i18n-loader` without using the namespace of `vue-i18n-loader`.

So far, I have contributed to vue ecosystem.
Using a prefix namespace called `vue-i18n` might be help vue community.

I had started the project focused on i18n called intlify.
From now on, I would like to take advantage of my experience and my ideas to offer for i18n solutions as OSS for no framework dependencies and no platform dependencies.
In near future, I'll plan to release some libraries and tools.

And we will continue to support libraries and tools for the vue ecosystem.
